name: Create-Screenshot

on:
  push:
  pull_request:

jobs:
  screenshot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install pelican
      run: |
        python -m pip install --upgrade pip
        python -m pip install "pelican[markdown]"
    - run: |
        pelican sample/content -s sample/settings.py -t .
        pelican --listen
    - name: Take screenshot
      uses: swinton/screenshot-website@v1.x
      with:
        source: http://localhost:8000
        destination: screenshot.png
