name: Create-Screenshot

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install pelican
      run: |
        python -m pip install --upgrade pip
        python -m pip install "pelican[markdown]"
    - run: |
        pelican sample/content -s sample/settings.py -t .
        pelican --listen &
    - name: Setup Node
      uses: actions/setup-node@v3
    - run: npm install --global capture-website-cli
    - run: capture-website "http://127.0.0.1:8000" --output "screenshot.png"
    - run: pwd
    - run: ls
    - name: Upload screenshot
      uses: genietim/ftp-action@releases/v2
      with:
        host: ${{ secrets.FTP_SERVER }}
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        localdir: "/home/runner/work/_temp/screenshot.png"
        remoteDir: "/"
