name: Create-Screenshot

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install pelican
      run: |
        python -m pip install --upgrade pip
        python -m pip install "pelican[markdown]"
    - run: |
        pelican sample/content -s sample/settings.py -t .
        pelican --listen &
    - name: Take screenshot
      uses: swinton/screenshot-website@v1.x
      with:
        source: http://localhost:8000
        destination: screenshot.png
    - name: Upload screenshot
      uses: genietim/ftp-action@releases/v2
      with:
        host: ${{ secrets.FTP_SERVER }}
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        localdir: outputs.path.value
        remoteDir: "/"
